title: Middleware Tips
email: your-email@example.com
description: Middleware Notes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://miservers.github.io"
twitter_username: jekyllrb
github_username:  jekyll

theme: minima
sass:
  sass_dir: _sass
include: ['docs']
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


