- name: Test Condition
  hosts: localhost
  vars:
    - file_name: myfile
    - foo: 'fou'
  
  tasks:

    - name: Register a variable
      shell: cat /etc/os-release
      register: os_release_contents

    - name: Test on registered variable
      debug:
        msg: os-release contains the word Ubuntu
      when: os_release_contents.stdout.find('Ubuntu') != -1

    - name: List contents of directory
      command: ls mydir
      register: contents
      ignore_errors: true

    - name: Check contents for emptiness
      debug:
        msg: "Directory is empty or not exist"
      when: contents.stdout == ""

    - name: Check if the file exists
      command: ls /tmp/{{ file_name }} 
      register: myfile_exists
      ignore_errors: yes
    
    - debug:
        var: myfile_exists

    - name: Create the file
      file:
        path: /tmp/{{ file_name }}
        state: touch
      when: myfile_exists is failed
      
    - name: show a message when the file exist
      debug:
        msg: /tmp/{{ file_name }} already exists
      when: myfile_exists is succeeded

    #- debug:
    #    var: ansible_facts  

    - name: Message if Debian installed
      debug:
        msg: "Your OS version is {{ ansible_facts.distribution }}  {{ansible_facts.distribution_version }}"
      when: ansible_facts['distribution'] == "Ubuntu" and 
            ansible_facts['distribution_major_version'] == "22"

    - name: Run the command if "foo" is defined
      debug:
        msg: "I've got '{{ foo }}' and am not afraid to use it!"
      when: foo is defined

    - name: Fail if "bar" is undefined
      fail: msg="Bailing out. This play requires 'bar'"
      when: bar is undefined