---
- name: Download Tomcat10 from tomcat.apache.org
  hosts: appservers
  vars:
    tomcat_binary: /home/jadmin/software/apache-tomcat-10.1.20.tar.gz
    tomcat_http_port: 8180
    catalina_home: /opt/tomcat10
    java_home: /opt/jdk
    java_opts:
    catalina_opts:
  tasks:
  
   - name: Create the group
     become: yes
     group: 
      name: tomcat
      state: present

   - name: Create the user
     become: yes
     user:
        name: tomcat
        password: $5$CBFXJeNVZMz7SL46$yJJHz1OIyBNM30fRtndO4e8nLb/HPUQMbFu3hmRmx26
        state: present

   - name: Setup the the JAVA_HOME
     blockinfile:
       path: /home/tomcat/.bash_profile
       insertafter: 'EOF'
       block: |
         export JAVA_HOME=/opt/jdk
         export PATH=$JAVA_HOME/bin:$PATH

   - name: Delete /opt/tomcat10
     file:
       path: "{{ catalina_home }}"
       state: absent

   - name: Create a Directory /opt/tomcat10
     become: yes
     file:
       path: "{{ catalina_home }}"
       state: directory
       mode: 0755
       owner: tomcat
       group: tomcat

   - name: Download Tomcat using unarchive
     become: yes
     unarchive:
       src: "{{tomcat_binary}}"
       dest: '{{catalina_home}}'
       mode: 0755
       copy: yes
       group: tomcat
       owner: tomcat
    
   - name: Move files to the /opt/tomcat10 directory
     become: yes
     become_user: tomcat
     shell: "mv -f {{catalina_home}}/apache*/* {{catalina_home}}/"
   
   - name: Apply server.xml Template
     template:
       src: templates/server.xml.j2
       dest: "{{catalina_home}}/conf/server.xml"

   - name: Apply setenv.sh Template
     template:
       src: templates/setenv.sh.j2
       dest: "{{catalina_home}}/bin/setenv.sh"

   - name: Start Tomcat
     become: yes
     become_user: tomcat
     shell: "{{ catalina_home }}/bin/startup.sh"

   - name: "Connect to Tomcat server on port {{tomcat_http_port}} and check status 200 - Try 5 times"
     tags: test
     uri:
       url: "http://localhost:{{tomcat_http_port}}"
     register: result
     until: "result.status == 200"
     retries: 5
     delay: 10
   
   - name: Stop Tomcat
     become: yes
     become_user: tomcat
     shell: "{{ catalina_home }}/bin/shutdown.sh"


